# Generated by Django 5.2.7 on 2025-11-06 02:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(help_text='Stored filename', max_length=255)),
                ('original_filename', models.CharField(help_text='Original uploaded filename', max_length=255)),
                ('file_size', models.BigIntegerField(help_text='File size in bytes')),
                ('mime_type', models.CharField(max_length=100)),
                ('storage_path', models.CharField(help_text='Path in Supabase Storage', max_length=500)),
                ('storage_url', models.URLField(help_text='Public URL from Supabase', max_length=500)),
                ('bucket_id', models.CharField(default='user-files', max_length=100)),
                ('file_category', models.CharField(choices=[('document', 'Document'), ('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('archive', 'Archive'), ('other', 'Other')], default='document', max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional file metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Uploaded File',
                'verbose_name_plural': 'Uploaded Files',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='api_uploade_user_id_459bfa_idx'), models.Index(fields=['file_category'], name='api_uploade_file_ca_62ebd4_idx'), models.Index(fields=['mime_type'], name='api_uploade_mime_ty_a3652a_idx')],
            },
        ),
    ]
